app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# FOS USER
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

# PROFILE
profile_urlname:
    path: /{urlname}
    defaults: { _controller: AppBundle:Profile:view }
    requirements:
        urlname: %urlname_regex%


# LIIP IMAGINE
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
