app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
lucky:
    path:     /lucky
    defaults: { _controller: AppBundle:Lucky:index }
    
home: 
    path:     /home
    defaults: { _controller: HomeBundle:Default:index }