app:
    resource: "@AppBundle/Controller/"
    type:     annotation

lucky:
    path:     /lucky
    defaults: { _controller: AppBundle:Lucky:index }

home:
    path:     /home
    defaults: { _controller: HomeBundle:Default:index }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
